# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
citi_data_path = os.path.relpath("../Weather/output_data/cities.csv")
citi_data = pd.read_csv (citi_data_path)
citi_data.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Ushuaia,40,AR,1650677100,75,-54.8000,-68.3000,42.46,2.30
1,1,San Patricio,33,US,1650677101,81,28.0170,-97.5169,77.09,18.25
2,2,Butaritari,12,KI,1650677101,72,3.0707,172.7902,82.62,19.64
3,3,Abu Samrah,89,SY,1650677101,19,35.3029,37.1841,63.50,4.83
4,4,Busselton,0,AU,1650677086,59,-33.6500,115.3333,63.46,13.62

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
locs = citi_data[["Lat","Lng"]]
wght = citi_data["Humidity"]
fig_lay = {
    'width': '800px',
    'height': '500px',
    'border': '1px solid black',
    'padding': '1px'
}
img = gmaps.figure(map_type="TERRAIN", layout = fig_lay)

img.add_layer(gmaps.heatmap_layer(locs, weights = wght))
img

Figure(layout=FigureLayout(border='1px solid black', height='500px', padding='1px', width='800px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [15]:
my_weath = citi_data.loc[((citi_data['Humidity'] < 60) & (citi_data['Max Temp'] < 60)
                           & (citi_data['Cloudiness'] > 50))]
my_weath_cle = my_weath.dropna()
my_weath_cle2 = my_weath_cle.iloc[0:10 , :]
my_weath_cle2

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
39,39,Mataura,51,NZ,1650677109,57,-46.1927,168.8643,58.48,8.12
40,40,Khovd,92,MN,1650677110,43,48.0056,91.6419,39.69,5.53
52,52,La Ronge,75,CA,1650677113,49,55.1001,-105.2842,44.85,5.75
62,62,Sosnovo-Ozerskoye,100,RU,1650677116,31,52.5249,111.5418,32.16,5.50
70,70,AtasÅ«,100,KZ,1650677117,50,48.6814,71.6433,46.13,10.20
114,114,Altay,100,CN,1650677128,49,47.8667,88.1167,40.80,2.04
123,123,General Roca,100,AR,1650677131,47,-39.0333,-67.5833,59.63,27.36
130,130,Berea,100,US,1650677133,59,41.3662,-81.8543,58.39,9.22
172,172,Athabasca,92,CA,1650677143,54,54.7169,-113.2854,50.41,8.10
185,185,YabrÅ«d,100,SY,1650677147,22,33.9674,36.6574,57.79,0.89

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [16]:
hotel_df = my_weath_cle2
# tar_lat = my_weath_cle.iloc[0 , 6]
# tar_lon = my_weath_cle.iloc[0 , 7]
# tar_loc = f"{tar_lat},{tar_lon}"
tar_rad = 5000
tar_type = "hotel"
hotels = []

# tar_param = {"location": tar_loc,
#     "radius": tar_rad,
#     "type": tar_type,
#     "key": g_key}

goomap_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
#test = requests.get(goomap_url, params=tar_param).json()

In [17]:
# testr = test.json()
# pprint.pprint(test["results"][0]["name"])
# pprint.pprint(testr["results"][0]["geometry"]["location"]["lat"])
# pprint.pprint(testr["results"][0]["geometry"]["location"]["lng"])

In [18]:
for i in my_weath_cle2.index:
    tar_lat =  my_weath_cle2["Lat"][i]
    tar_lon = my_weath_cle2["Lng"][i]
    tar_loc = f"{tar_lat},{tar_lon}"
    tar_param = {"location": tar_loc,"radius": tar_rad,"type": tar_type,"key": g_key}
    test = requests.get(goomap_url, params=tar_param).json()
    hotels.append(test["results"][0]["name"])
hotel_df["Hotel Name"] = hotels

C:\Users\CHRISP~1\AppData\Local\Temp/ipykernel_19704/2982284701.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = hotels

In [19]:
hotel_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
39,39,Mataura,51,NZ,1650677109,57,-46.1927,168.8643,58.48,8.12,Gore
40,40,Khovd,92,MN,1650677110,43,48.0056,91.6419,39.69,5.53,Khovd
52,52,La Ronge,75,CA,1650677113,49,55.1001,-105.2842,44.85,5.75,La Ronge
62,62,Sosnovo-Ozerskoye,100,RU,1650677116,31,52.5249,111.5418,32.16,5.50,Sosnovo-Ozerskoe
70,70,AtasÅ«,100,KZ,1650677117,50,48.6814,71.6433,46.13,10.20,Atasu
114,114,Altay,100,CN,1650677128,49,47.8667,88.1167,40.80,2.04,Altay Prefecture
123,123,General Roca,100,AR,1650677131,47,-39.0333,-67.5833,59.63,27.36,General Roca
130,130,Berea,100,US,1650677133,59,41.3662,-81.8543,58.39,9.22,Strongsville
172,172,Athabasca,92,CA,1650677143,54,54.7169,-113.2854,50.41,8.10,Athabasca
185,185,YabrÅ«d,100,SY,1650677147,22,33.9674,36.6574,57.79,0.89,Yabrud

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map
marks = gmaps.marker_layer(locations, info_box_content=hotel_info)
img.add_layer(marks)

# Display figure
img

Figure(layout=FigureLayout(border='1px solid black', height='500px', padding='1px', width='800px'))